/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
 * Generated on: 12-Jun-2018 20:59:13
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 21
 * Denominator Length  : 21
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013b\extern\include\tmwtypes.h 
 */
const int NL = 21;
const double NUM[21] = {
  2.867384400357e-12,5.734768800714e-11,5.448030360678e-10,3.268818216407e-09,
  1.389247741973e-08,4.445592774313e-08,1.111398193578e-07,2.222796387157e-07,
   3.61204412913e-07, 4.81605883884e-07,5.297664722723e-07, 4.81605883884e-07,
   3.61204412913e-07,2.222796387157e-07,1.111398193578e-07,4.445592774313e-08,
  1.389247741973e-08,3.268818216407e-09,5.448030360678e-10,5.734768800714e-11,
  2.867384400357e-12
};
const int DL = 21;
const double DEN[21] = {
                   1,   -11.99378017162,    69.41165644869,   -257.3693258566,
      684.9148471655,    -1389.21626524,    2226.486426182,    -2885.15331847,
      3068.102191284,   -2702.317142789,    1981.137693847,   -1210.501541604,
      615.1008807534,   -258.4187123042,     88.8556606349,   -24.61260608736,
      5.361835809716,  -0.8851266245437,   0.1041357771743,-0.007783676685313,
  0.0002779267153158
};
